[target]
target01 ansible_host=10.30.0.20 ansible_user=alumno ansible_password=alumno ansible_become_password=alumno

[target:vars]
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
